# Built with Jekyll 3.6.0

# Site Metadata
title:               "Pathways to Arts and Humanities"
tagline:             "Summer 2025"
description:         "A collection of writings by high school students enrolled in the workshop Storytelling Today: Literature Beyond Books."
url:                 "https://ypah-s25.github.io"
baseurl:             "/storytelling" # Adjust to match your GitHub repository name if it's hosted in a subdirectory.

# About/Contact Information
author:
  name:              "Luis Prieto"
  url:               "https://ypah-s25.github.io/storytelling"
  email:             "luis.prieto@yale.edu"

# Color Scheme for the Theme (Options: red, orange, magenta, cyan, blue, brown)
color-scheme: blue        

# Permalinks Configuration
permalink: pretty
permalink:           "/:ypah-s25/:storytelling/" 

# Site Encoding
encoding:            "utf-8"

# Collections Configuration for Texts
collections:
  texts:
    output: true
    permalink: "/texts/:title/" # Organize the texts collection with clean permalinks

# Markdown Processor and Options
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the Final Site Build
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme Configuration
# Uncomment the `theme` line if using the Ed. theme locally or on a custom server
# theme: "ed."

# Remote Theme for GitHub Deployments
remote_theme: minicomp/ed

# Plugins Configuration
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # Uncomment jekyll-scholar if you need bibliography support and have resolved potential conflicts
  # - jekyll-scholar
